In [17]:
!pip install opencv-python


import scipy.io
import pandas as pd
from numpy.linalg import inv
import numpy as np
from numpy.linalg import matrix_rank
from numpy.linalg import svd
from scipy import linalg
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

mat = scipy.io.loadmat('girosmallveryslow2.mp4_features.mat')
df = pd.DataFrame(mat['features'])
Matrix = df.to_numpy()
Base = Matrix[:,5894:5906]
Matrix.shape

(512, 10482)

In [5]:
rank_B = matrix_rank(Base) # Get rank from the MAtrix
# Projection on to the subspace

C = np.matmul(inv(np.matmul(Base.T,Base)),np.matmul(Base.T,Matrix ))
P = np.matmul(Base, C) #Calculate b prependicular
R = np.subtract(Matrix,P)
print(Base)
NormP = np.linalg.norm(P, axis =0)
index_Pnorm_sorted = np.argsort(NormP, axis=0)
NormR = np.linalg.norm(R, axis =0)
index_Rnorm_sorted = np.argsort(NormR, axis=0)

rank_B
Base.shape

[[1.8000458  2.26594    1.8627845  ... 2.197496   2.5490172  2.4853127 ]
 [0.02794812 0.15555473 0.22973426 ... 0.22001772 0.22537997 0.21277605]
 [0.03847306 0.1561261  0.04150863 ... 0.6754089  0.87902683 0.84594303]
 ...
 [0.05752653 0.08565312 0.08887959 ... 0.24699141 0.05551713 0.14446455]
 [0.30677146 0.19653176 0.34869042 ... 0.58008075 0.44082928 0.54057395]
 [0.33480862 0.16423725 0.21740076 ... 0.29398447 0.52627003 0.2571485 ]]


(512, 12)

In [6]:
# Reduce the number of the Base Matrix SVD
u, s, vh = np.linalg.svd(Base)
u.shape, s.shape, vh.shape
s_lowrank = s[:3]
s_lowrank = np.diag(s_lowrank)
vh_lowrank = vh[:3]
u_lowrank = u[:,:3]
u_lowrank.shape, s_lowrank.shape, vh_lowrank.shape
Base_lowrank = np.matmul(np.matmul(u_lowrank,s_lowrank), vh_lowrank)
Base_lowrank.shape

[[-1.8558766e-01  1.3577907e-01  5.8508340e-02 ... -7.7937060e-05
  -3.0609667e-02 -5.0071865e-02]
 [-1.6463445e-02  2.4178680e-02 -1.1397492e-03 ... -1.1074624e-04
   2.6737183e-02  4.4702236e-02]
 [-3.2005031e-02  1.2402420e-01  6.0136709e-02 ... -1.2932642e-03
   4.2652082e-02  1.4644236e-02]
 ...
 [-1.1656550e-02  1.5909063e-02 -8.6552063e-03 ...  9.9321187e-01
  -4.2372962e-04  4.1587842e-03]
 [-3.4648839e-02  8.5225560e-02 -3.3765949e-02 ... -3.0270829e-03
   9.6604806e-01 -7.9904305e-04]
 [-2.1394221e-02  1.0687318e-02  3.3725325e-02 ...  4.7195307e-03
  -2.3496354e-03  9.7629094e-01]]


(512, 12)

In [14]:
import cv2

vidcap = cv2.VideoCapture('girosmallveryslow2.mp4')
success,image = vidcap.read()
count = 0

while success:
  cv2.imwrite("frame%d.jpg" % count, image)     # save frame as JPEG file      
  success,image = vidcap.read()
  print('Read a new frame: ', success)
  count += 1

ModuleNotFoundError: No module named 'cv2'

### Detection of outliers

In [ ]:
#Calculate orthogonal projection on to the Subspace
PI = np.dot(Base,np.inv(Base.T,Base))